[package]
name = "watermelon"
version = "0.0.1"
authors = [ "Brian Arpie <brian.arpie@gmail.com>" ]

[[bin]]
name = "watermelon"
path = "src/watermelon.rs"

[dependencies.color]
git = "https://github.com/bjz/color-rs.git"
